### PR TITLE
added Promise

### PR DESCRIPTION
**Pull request by rianby64**
At line 20 gulp-usemin/lib/htmlBuilder.js you've "return new Promise(function(resolve) { ... " and there's no definition for Promise. I added it.

### CODE REVIEW

**Comment by zont** [comment]
Node >= 0.12 support native promises

**Comment by timwis** [comment]
I ran into this issue too... could you add fallback support if Promise isn't defined? I'm on v0.10

**Comment by zont** [comment]
Can you create pull request?

**Comment by timwis** [comment]
Sure, although in researching this I came across these two posts which suggest native promises may not be the best option yet:
* http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird
* http://stackoverflow.com/questions/21564993/native-support-for-promises-in-node-js

Thoughts?

**Pull request closed without merging**
